/*
@license
dhtmlxScheduler.Net v.3.3.0 Professional Evaluation

This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
scheduler.config.multisection=!0,scheduler.config.multisection_shift_all=!0,scheduler.config.section_delemiter=",",scheduler.attachEvent("onSchedulerReady",function(){var e=scheduler._update_unit_section;scheduler._update_unit_section=function(t){return scheduler._update_sections(t,e)};var t=scheduler._update_timeline_section;scheduler._update_timeline_section=function(e){return scheduler._update_sections(e,t)},scheduler.isMultisectionEvent=function(e){if(e&&this._get_multisection_view()){var t=this._get_event_sections(e);
return t.length>1}return!1},scheduler._get_event_sections=function(e){var t=this._get_section_property(),a=e[t]||"";return this._parse_event_sections(a)},scheduler._parse_event_sections=function(e){return e instanceof Array?e:e.toString().split(scheduler.config.section_delemiter)},scheduler._register_copies_array=function(e){for(var t=0;t<e.length;t++)this._register_copy(e[t])},scheduler._register_copy=function(e){this._multisection_copies[e.id]||(this._multisection_copies[e.id]={});var t=e[this._get_section_property()],a=this._multisection_copies[e.id];
a[t]||(a[t]=e)},scheduler._get_copied_event=function(e,t){if(!this._multisection_copies[e])return null;if(this._multisection_copies[e][t])return this._multisection_copies[e][t];var a=this._multisection_copies[e];if(scheduler._drag_event&&scheduler._drag_event._orig_section&&a[scheduler._drag_event._orig_section])return a[scheduler._drag_event._orig_section];var n=1/0,i=null;for(var r in a)a[r]._sorder<n&&(i=a[r],n=a[r]._sorder);return i},scheduler._clear_copied_events=function(){this._multisection_copies={}
},scheduler._clear_copied_events(),scheduler._split_events=function(e){var t=[],a=this._get_multisection_view(),n=this._get_section_property();if(a)for(var i=0;i<e.length;i++){var r=this._get_event_sections(e[i]);if(r.length>1){for(var s=0;s<r.length;s++)if("undefined"!=typeof a.order[r[s]]){var d=this._lame_copy({},e[i]);d[n]=r[s],t.push(d)}}else t.push(e[i])}else t=e;return t},scheduler._get_multisection_view=function(){return this.config.multisection?scheduler._get_section_view():!1};var a=scheduler.get_visible_events;
scheduler.get_visible_events=function(){this._clear_copied_events();var e=a.apply(this,arguments);if(this._get_multisection_view()){e=this._split_events(e);for(var t=0;t<e.length;t++)this.is_visible_events(e[t])||(e.splice(t,1),t--);this._register_copies_array(e)}return e},scheduler._rendered_events={};var n=scheduler.render_view_data;scheduler.render_view_data=function(e,t){return this._get_multisection_view()&&e&&(e=this._split_events(e),this._restore_render_flags(e)),n.apply(this,[e,t])},scheduler._restore_render_flags=function(e){for(var t=this._get_section_property(),a=0;a<e.length;a++){var n=e[a],i=scheduler._get_copied_event(n.id,n[t]);
if(i)for(var r in i)0===r.indexOf("_")&&(n[r]=i[r])}},scheduler._update_sections=function(e,t){var a=e.view,n=e.event,i=e.pos;if(scheduler.isMultisectionEvent(n)){if(scheduler._drag_event._orig_section||(scheduler._drag_event._orig_section=i.section),scheduler._drag_event._orig_section!=i.section){var r=a.order[i.section]-a.order[scheduler._drag_event._orig_section];if(r){var s=this._get_event_sections(n),d=[],o=!0;if(scheduler.config.multisection_shift_all)for(var _=0;_<s.length;_++){var l=scheduler._shift_sections(a,s[_],r);
if(null===l){d=s,o=!1;break}d[_]=l}else for(var _=0;_<s.length;_++){if(s[_]==i.section){d=s,o=!1;break}if(s[_]==scheduler._drag_event._orig_section){var l=scheduler._shift_sections(a,s[_],r);if(null===l){d=s,o=!1;break}d[_]=l}else d[_]=s[_]}o&&(scheduler._drag_event._orig_section=i.section),n[scheduler._get_section_property()]=d.join(",")}}}else t.apply(scheduler,[e])},scheduler._shift_sections=function(e,t,a){for(var n=null,i=e.y_unit,r=0;r<i.length;r++)if(i[r].key==t){n=r;break}var s=i[n+a];return s?s.key:null
};var i=scheduler._get_blocked_zones;scheduler._get_blocked_zones=function(e,t,a,n,r){if(t&&this.config.multisection){t=this._parse_event_sections(t);for(var s=[],d=0;d<t.length;d++)s=s.concat(i.apply(this,[e,t[d],a,n,r]));return s}return i.apply(this,arguments)};var r=scheduler._check_sections_collision;scheduler._check_sections_collision=function(e,t){if(this.config.multisection&&this._get_section_view()){e=this._split_events([e]),t=this._split_events([t]);for(var a=!1,n=0,i=e.length;i>n&&!a;n++)for(var s=0,d=t.length;d>s;s++)if(r.apply(this,[e[n],t[s]])){a=!0;
break}return a}return r.apply(this,arguments)}});